'use client';

import { useDetailsSearchParams } from '@/app/hooks';
import { Drawer, FullScreenMain } from '@/components';
import { Canvas } from '@react-three/fiber';
import { AnimatePresence } from 'motion/react';
import { useCallback, useState } from 'react';
import { MathUtils } from 'three';
import { Scene } from './scene';
import { Controls } from './ui/controls';
import { ImageData } from './ui/image-data';

type Props = {
  initialText: string;
};

export function DuneIpsum({ initialText }: Props) {
  const [text, setText] = useState(initialText);

  const [position, setPosition] = useState<Float32Array | null>(null);

  const [isRendering, setIsRendering] = useState(true);

  const [areDetailsOpen] = useDetailsSearchParams();

  const handleImageData = useCallback(
    (imageData: ImageData, particleGap: number) => {
      // canvas image data is a one-dimensional array of RGBA values per pixel
      const pointCoords: number[] = [];

      let i = 0;

      while (i < imageData.data.length) {
        const alpha = imageData.data[i + 3];

        if (alpha > 0) {
          const x = ((i / 4) % imageData.width) - imageData.width / 2;
          const y = -((i / 4 - x) / imageData.width - imageData.height / 2);

          pointCoords.push(x, y - 25, 0);
        }

        i += MathUtils.randInt(1, particleGap) * 4;
      }

      setPosition(Float32Array.from(pointCoords));
    },
    [],
  );

  const handleComplete = useCallback(() => {
    setIsRendering(false);
  }, []);

  const handleGenerate = (newText: string) => {
    if (isRendering) {
      return;
    }

    setIsRendering(true);

    setText(newText);
  };

  return (
    <FullScreenMain>
      {position && (
        <Canvas
          orthographic={true}
          camera={{ position: [0, 0, 1], far: 500 }}
          resize={{ scroll: true, debounce: { scroll: 50, resize: 0 } }}
        >
          <Scene
            position={position}
            isRendering={isRendering}
            onComplete={handleComplete}
          />
        </Canvas>
      )}

      <div className="absolute top-0 left-0 flex h-full w-full flex-col pb-6">
        <Controls
          text={text}
          onGenerate={handleGenerate}
          disabled={isRendering}
        />

        <ImageData text={text} onChange={handleImageData} />
      </div>

      <AnimatePresence>
        {areDetailsOpen && (
          <Drawer>
            <p>
              A Dune-themed lorem ipsum generator built with react-three-fiber.
            </p>
            <p>
              Text is generated by ChatGPT and painted to an invisible canvas
              element, formatted to fit the screen. This allows the text to be
              sized, broken up, and positioned in a more reliable manner across
              varying screen sizes.
            </p>
            <p>
              From the canvas, pixel data is converted into position vectors.
              Each particle is associated with a time value that determines when
              it becomes visible (pixels further to the right generally become
              visible later).
            </p>
            <p>
              Finally, particles are rendered by a vertex shader utilizing the
              position values, while the "animation" is accomplished with a
              fragment shader that either paints or discards pixels based on
              elapsed time.
            </p>
          </Drawer>
        )}
      </AnimatePresence>
    </FullScreenMain>
  );
}
