'use client';

import { useDetailsSearchParams } from '@/app/hooks';
import { Drawer, FullScreenMain } from '@/components';
import { Canvas } from '@react-three/fiber';
import { AnimatePresence } from 'motion/react';
import { Suspense, useCallback, useState } from 'react';
import { MathUtils } from 'three';
import { write } from '../actions';
import { Incoming } from './scene/text/Incoming';
import { Outgoing } from './scene/text/Outgoing';
import { Wind } from './scene/wind';
import { type TextState } from './types';
import { Controls } from './ui/controls';
import { ImageData } from './ui/image-data';
import { createIncomingTextGeometry } from './utils';

type Props = {
  initialText: string;
};

export function DuneIpsum({ initialText }: Props) {
  const [text, setText] = useState(initialText);

  const [isRendering, setIsRendering] = useState(true);

  const [incomingTextState, setIncomingTextState] = useState<TextState | null>(
    null,
  );

  const [outgoingTextState, setOutgoingTextState] = useState<TextState | null>(
    null,
  );

  const [areDetailsOpen] = useDetailsSearchParams();

  const handleImageData = useCallback(
    (imageData: ImageData, particleGap: number) => {
      // canvas image data is a one-dimensional array of RGBA values per pixel
      const pointCoords: number[] = [];

      let i = 0;

      while (i < imageData.data.length) {
        const alpha = imageData.data[i + 3];

        if (alpha > 0) {
          const x = ((i / 4) % imageData.width) - imageData.width / 2;
          const y = -((i / 4 - x) / imageData.width - imageData.height / 2);

          pointCoords.push(x, y - 25, 0);
        }

        i += MathUtils.randInt(1, particleGap) * 4;
      }

      const position = Float32Array.from(pointCoords);

      setIncomingTextState((prev) => ({
        key: prev?.key ?? 0 + 1,
        ...createIncomingTextGeometry(position),
      }));
    },
    [],
  );

  const handleComplete = useCallback(() => {
    setIsRendering(false);
    setOutgoingTextState(null);
  }, []);

  const handleGenerate = async () => {
    if (isRendering) {
      return;
    }

    setIsRendering(true);

    setOutgoingTextState(incomingTextState);
    setIncomingTextState(null);

    const newText = await write();
    setText(newText);
  };

  return (
    <FullScreenMain>
      <Canvas
        orthographic={true}
        camera={{ position: [0, 0, 1], far: 500 }}
        resize={{ scroll: true, debounce: { scroll: 50, resize: 0 } }}
      >
        <Suspense fallback={null}>
          {incomingTextState && (
            <Incoming
              key={`incoming-${incomingTextState.key}`}
              geometry={incomingTextState.geometry}
              incomingDelay={2}
              maxVisibleTime={incomingTextState.maxVisibleTime}
              onComplete={handleComplete}
            />
          )}

          {outgoingTextState && (
            <Outgoing
              key={`outgoing-${outgoingTextState.key}`}
              geometry={outgoingTextState.geometry}
            />
          )}

          <Wind isRendering={isRendering} />
        </Suspense>
      </Canvas>

      <div className="absolute top-0 left-0 flex h-full w-full flex-col pb-6">
        <Controls
          text={text}
          onGenerate={handleGenerate}
          disabled={isRendering}
        />

        <ImageData text={text} onChange={handleImageData} />
      </div>

      <AnimatePresence>
        {areDetailsOpen && (
          <Drawer>
            <p>
              A Dune-themed lorem ipsum generator built with react-three-fiber.
            </p>
            <p>
              Text is generated by ChatGPT and painted to an invisible canvas
              element, formatted to fit the screen. This allows the text to be
              sized, broken up, and positioned in a more reliable manner across
              varying screen sizes.
            </p>
            <p>
              From the canvas, pixel data is converted into position vectors.
              Each particle is associated with a time value that determines when
              it becomes visible (pixels further to the right generally become
              visible later).
            </p>
            <p>
              Finally, particles are rendered by a vertex shader utilizing the
              position values, while the &quot;animation&quot; is accomplished
              with a fragment shader that either paints or discards pixels based
              on elapsed time.
            </p>
          </Drawer>
        )}
      </AnimatePresence>
    </FullScreenMain>
  );
}
